name: Cypress run on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

  # strategy:
  #     node-version: [14.17.0]
  #     # when one test fails, DO NOT cancel the other
  #     # containers, because this will kill Cypress processes
  #     # leaving the Dashboard hanging ...
  #     # https://github.com/cypress-io/github-action/issues/48
  #     fail-fast: false
  #     matrix:
  #       # run copies of the current job in parallel
  #       containers: [1, 2, 3, 4, 5]

  steps:
    # - name: Checkout repo
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # Create env file to use for build
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_apiKey: "AIzaSyAetzYr58dbTRipl5BFktCqOgEu9DyhclM"
        envkey_authDomain: "jurorsearch-staging.firebaseapp.com"
        envkey_projectId: "jurorsearch-staging"
        envkey_storageBucket: "jurorsearch-staging.appspot.com"
        envkey_messagingSenderId: "1026767447442"
        envkey_appId: "1:1026767447442:web:cb883ae06abb0e28cecd4b"
        envkey_measurementId: "G-PKRELT9WXZ"
        envkey_functionsUrl: "https://us-central1-jurorsearch-staging.cloudfunctions.net/api"
        # some_other_variable: foobar
        # directory: <directory_name>
        file_name: .env