name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     node-version: [8.x]
    #     # Set N number of parallel jobs you want to run tests on.
    #     # Use higher number if you have slow tests to split them on more parallel jobs.
    #     # Remember to update ci_node_index below to 0..N-1
    #     ci_node_total: [4]
    #     # set N-1 indexes for parallel jobs
    #     # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
    #     ci_node_index: [0, 1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies
      - name: Background Stuff
      - run: npx browserslist@latest --update-db
      
      # Create env file to use for build
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          apiKey: "AIzaSyAetzYr58dbTRipl5BFktCqOgEu9DyhclM"
          authDomain: "jurorsearch-staging.firebaseapp.com"
          projectId: "jurorsearch-staging"
          storageBucket: "jurorsearch-staging.appspot.com"
          messagingSenderId: "1026767447442"
          appId: "1:1026767447442:web:cb883ae06abb0e28cecd4b"
          measurementId: "G-PKRELT9WXZ"
          functionsUrl: "https://us-central1-jurorsearch-staging.cloudfunctions.net/api"
          # some_other_variable: foobar
          # directory: <directory_name>
          file_name: .env

      # Build the application

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests on test
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}